#!/usr/bin/env python3
"""Small, dependency-free helper for recording the hackathon demo.

Run these commands from the repository root:
    python3 demo.py reset
    python3 demo.py prepare
    python3 run.py demo_input demo_output
    python3 demo.py verify
    python3 demo.py show
"""

from __future__ import annotations

import argparse
import shutil
from pathlib import Path

import numpy as np


DEMO_INPUT = Path("demo_input")
DEMO_OUTPUT = Path("demo_output")
DEMO_VIEW = Path("demo_view")


def selected_input() -> Path:
    """Return the one array staged for the short live demo."""
    paths = sorted(DEMO_INPUT.glob("*.npy"))
    if len(paths) != 1:
        raise SystemExit(
            "Expected exactly one .npy file in demo_input. "
            "Run `python3 demo.py prepare` first."
        )
    return paths[0]


def prepare(source_dir: Path) -> None:
    paths = sorted(source_dir.glob("*.npy"))
    if not paths:
        raise SystemExit(f"No .npy files found in {source_dir}")
    DEMO_INPUT.mkdir(exist_ok=True)
    # Keep the demo deterministic and easy to explain: one input, one output.
    for old_path in DEMO_INPUT.glob("*.npy"):
        old_path.unlink()
    source = paths[0]
    destination = DEMO_INPUT / source.name
    shutil.copy2(source, destination)
    print(f"Prepared demo input: {destination}")


def reset() -> None:
    """Remove only files generated by this demo helper."""
    for directory in (DEMO_INPUT, DEMO_OUTPUT, DEMO_VIEW):
        if directory.exists() and not directory.is_dir():
            raise SystemExit(f"Refusing to remove {directory}: expected a directory")
        if directory.is_dir():
            shutil.rmtree(directory)
    print("Demo reset complete.")


def verify() -> None:
    input_path = selected_input()
    output_path = DEMO_OUTPUT / input_path.name
    if not output_path.is_file():
        raise SystemExit(f"Missing expected output: {output_path}")
    source = np.load(input_path, allow_pickle=False)
    restored = np.load(output_path, allow_pickle=False)
    source_shape = source.shape[:2]
    expected_shape = (source_shape[0] * 2, source_shape[1] * 2)
    if restored.shape not in (expected_shape, (*expected_shape, 1)):
        raise SystemExit(f"Wrong output shape: {restored.shape}; expected {expected_shape}")
    if not np.isfinite(restored).all() or restored.min() < 0 or restored.max() > 1:
        raise SystemExit("Output contains invalid values; expected finite values in [0, 1]")
    print("OUTPUT CONTRACT PASSED")
    print(f"filename preserved: {input_path.name}")
    print(f"input:  shape={source.shape}, dtype={source.dtype}")
    print(
        f"output: shape={restored.shape}, dtype={restored.dtype}, "
        f"range=[{restored.min():.4f}, {restored.max():.4f}], finite=True"
    )


def display_u8(array: np.ndarray) -> np.ndarray:
    """Contrast-normalize an array for display only; inference values remain unchanged."""
    array = np.nan_to_num(array.astype(np.float32, copy=False))
    low, high = np.percentile(array, [1, 99])
    normalized = np.clip((array - low) / max(high - low, 1e-8), 0.0, 1.0)
    return (normalized * 255.0 + 0.5).astype(np.uint8)


def show() -> None:
    input_path = selected_input()
    output_path = DEMO_OUTPUT / input_path.name
    if not output_path.is_file():
        raise SystemExit("Run `python3 run.py demo_input demo_output` before creating the view.")
    source = np.load(input_path, allow_pickle=False)
    restored = np.load(output_path, allow_pickle=False)
    if source.ndim == 3:
        source = source[..., 0]
    if restored.ndim == 3:
        restored = restored[..., 0]
    enlarged_input = np.repeat(np.repeat(source, 2, axis=0), 2, axis=1)
    separator = np.full((restored.shape[0], 12), 255, dtype=np.uint8)
    comparison = np.concatenate(
        [display_u8(enlarged_input), separator, display_u8(restored)], axis=1
    )
    DEMO_VIEW.mkdir(exist_ok=True)
    image_path = DEMO_VIEW / "input_vs_restored.pgm"
    with image_path.open("wb") as handle:
        height, width = comparison.shape
        handle.write(f"P5\n{width} {height}\n255\n".encode())
        handle.write(comparison.tobytes())
    print(f"Created display image: {image_path}")
    print("Left = degraded input enlarged 2x | Right = restored output")
    print("On macOS, open it with: open demo_view/input_vs_restored.pgm")


def main() -> None:
    parser = argparse.ArgumentParser(description="Prepare and verify the short hackathon demo.")
    subparsers = parser.add_subparsers(dest="command", required=True)
    subparsers.add_parser("reset", help="Remove only generated demo files and folders")
    prepare_parser = subparsers.add_parser("prepare", help="Stage one supplied test input")
    prepare_parser.add_argument("--source-dir", type=Path, default=Path("data/test/NoisyLR"))
    subparsers.add_parser("verify", help="Check filename, shape, dtype, and output range")
    subparsers.add_parser("show", help="Create a side-by-side visual comparison")
    args = parser.parse_args()
    if args.command == "reset":
        reset()
    elif args.command == "prepare":
        prepare(args.source_dir)
    elif args.command == "verify":
        verify()
    else:
        show()


if __name__ == "__main__":
    main()
